// Code generated by ogen, DO NOT EDIT.

package oas

// OperationName is the ogen operation name
type OperationName = string

const (
	AcknowledgeAlertOperation        OperationName = "AcknowledgeAlert"
	CancelExecutionOperation         OperationName = "CancelExecution"
	CreateAlertOperation             OperationName = "CreateAlert"
	CreateWorkflowOperation          OperationName = "CreateWorkflow"
	DeleteWorkflowOperation          OperationName = "DeleteWorkflow"
	ExecuteWorkflowOperation         OperationName = "ExecuteWorkflow"
	GetAlertOperation                OperationName = "GetAlert"
	GetExecutionOperation            OperationName = "GetExecution"
	GetWorkflowOperation             OperationName = "GetWorkflow"
	HealthCheckOperation             OperationName = "HealthCheck"
	ListAlertsOperation              OperationName = "ListAlerts"
	ListAuditLogsOperation           OperationName = "ListAuditLogs"
	ListAuditLogsByResourceOperation OperationName = "ListAuditLogsByResource"
	ListAuditLogsByUserOperation     OperationName = "ListAuditLogsByUser"
	ListExecutionsOperation          OperationName = "ListExecutions"
	ListWorkflowExecutionsOperation  OperationName = "ListWorkflowExecutions"
	ListWorkflowsOperation           OperationName = "ListWorkflows"
	LivenessProbeOperation           OperationName = "LivenessProbe"
	ReadinessProbeOperation          OperationName = "ReadinessProbe"
	ResolveAlertOperation            OperationName = "ResolveAlert"
	UpdateWorkflowOperation          OperationName = "UpdateWorkflow"
)
