// Code generated by ogen, DO NOT EDIT.
package oas

type AcknowledgeAlertRes interface {
	acknowledgeAlertRes()
}

type CancelExecutionRes interface {
	cancelExecutionRes()
}

type CreateAlertRes interface {
	createAlertRes()
}

type CreateWorkflowRes interface {
	createWorkflowRes()
}

type DeleteWorkflowRes interface {
	deleteWorkflowRes()
}

type ExecuteWorkflowRes interface {
	executeWorkflowRes()
}

type GetAlertRes interface {
	getAlertRes()
}

type GetExecutionRes interface {
	getExecutionRes()
}

type GetWorkflowRes interface {
	getWorkflowRes()
}

type HealthCheckRes interface {
	healthCheckRes()
}

type ListAlertsRes interface {
	listAlertsRes()
}

type ListAuditLogsByResourceRes interface {
	listAuditLogsByResourceRes()
}

type ListAuditLogsByUserRes interface {
	listAuditLogsByUserRes()
}

type ListAuditLogsRes interface {
	listAuditLogsRes()
}

type ListExecutionsRes interface {
	listExecutionsRes()
}

type ListWorkflowExecutionsRes interface {
	listWorkflowExecutionsRes()
}

type ListWorkflowsRes interface {
	listWorkflowsRes()
}

type LivenessProbeRes interface {
	livenessProbeRes()
}

type ReadinessProbeRes interface {
	readinessProbeRes()
}

type ResolveAlertRes interface {
	resolveAlertRes()
}

type UpdateWorkflowRes interface {
	updateWorkflowRes()
}
