// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"time"

	"github.com/go-faster/errors"
	"github.com/go-faster/jx"
	"github.com/google/uuid"
)

type AcknowledgeAlertInternalServerError Error

func (*AcknowledgeAlertInternalServerError) acknowledgeAlertRes() {}

type AcknowledgeAlertNotFound Error

func (*AcknowledgeAlertNotFound) acknowledgeAlertRes() {}

type AcknowledgeAlertUnauthorized Error

func (*AcknowledgeAlertUnauthorized) acknowledgeAlertRes() {}

type AcknowledgeAlertUnprocessableEntity Error

func (*AcknowledgeAlertUnprocessableEntity) acknowledgeAlertRes() {}

// System alert for workflow events.
// Ref: #/components/schemas/Alert
type Alert struct {
	// Unique alert identifier.
	ID uuid.UUID `json:"id"`
	// Tenant identifier.
	TenantID uuid.UUID `json:"tenant_id"`
	// Related workflow (if any).
	WorkflowID OptNilUUID `json:"workflow_id"`
	// Related execution (if any).
	ExecutionID OptNilUUID    `json:"execution_id"`
	Severity    AlertSeverity `json:"severity"`
	// Alert title.
	Title string `json:"title"`
	// Detailed alert message.
	Message OptNilString `json:"message"`
	Status  AlertStatus  `json:"status"`
	// When the alert was acknowledged.
	AcknowledgedAt OptNilDateTime `json:"acknowledged_at"`
	// User who acknowledged.
	AcknowledgedBy OptNilUUID `json:"acknowledged_by"`
	// When the alert was resolved.
	ResolvedAt OptNilDateTime `json:"resolved_at"`
	// User who resolved.
	ResolvedBy OptNilUUID `json:"resolved_by"`
	// Creation timestamp.
	CreatedAt time.Time `json:"created_at"`
}

// GetID returns the value of ID.
func (s *Alert) GetID() uuid.UUID {
	return s.ID
}

// GetTenantID returns the value of TenantID.
func (s *Alert) GetTenantID() uuid.UUID {
	return s.TenantID
}

// GetWorkflowID returns the value of WorkflowID.
func (s *Alert) GetWorkflowID() OptNilUUID {
	return s.WorkflowID
}

// GetExecutionID returns the value of ExecutionID.
func (s *Alert) GetExecutionID() OptNilUUID {
	return s.ExecutionID
}

// GetSeverity returns the value of Severity.
func (s *Alert) GetSeverity() AlertSeverity {
	return s.Severity
}

// GetTitle returns the value of Title.
func (s *Alert) GetTitle() string {
	return s.Title
}

// GetMessage returns the value of Message.
func (s *Alert) GetMessage() OptNilString {
	return s.Message
}

// GetStatus returns the value of Status.
func (s *Alert) GetStatus() AlertStatus {
	return s.Status
}

// GetAcknowledgedAt returns the value of AcknowledgedAt.
func (s *Alert) GetAcknowledgedAt() OptNilDateTime {
	return s.AcknowledgedAt
}

// GetAcknowledgedBy returns the value of AcknowledgedBy.
func (s *Alert) GetAcknowledgedBy() OptNilUUID {
	return s.AcknowledgedBy
}

// GetResolvedAt returns the value of ResolvedAt.
func (s *Alert) GetResolvedAt() OptNilDateTime {
	return s.ResolvedAt
}

// GetResolvedBy returns the value of ResolvedBy.
func (s *Alert) GetResolvedBy() OptNilUUID {
	return s.ResolvedBy
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Alert) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// SetID sets the value of ID.
func (s *Alert) SetID(val uuid.UUID) {
	s.ID = val
}

// SetTenantID sets the value of TenantID.
func (s *Alert) SetTenantID(val uuid.UUID) {
	s.TenantID = val
}

// SetWorkflowID sets the value of WorkflowID.
func (s *Alert) SetWorkflowID(val OptNilUUID) {
	s.WorkflowID = val
}

// SetExecutionID sets the value of ExecutionID.
func (s *Alert) SetExecutionID(val OptNilUUID) {
	s.ExecutionID = val
}

// SetSeverity sets the value of Severity.
func (s *Alert) SetSeverity(val AlertSeverity) {
	s.Severity = val
}

// SetTitle sets the value of Title.
func (s *Alert) SetTitle(val string) {
	s.Title = val
}

// SetMessage sets the value of Message.
func (s *Alert) SetMessage(val OptNilString) {
	s.Message = val
}

// SetStatus sets the value of Status.
func (s *Alert) SetStatus(val AlertStatus) {
	s.Status = val
}

// SetAcknowledgedAt sets the value of AcknowledgedAt.
func (s *Alert) SetAcknowledgedAt(val OptNilDateTime) {
	s.AcknowledgedAt = val
}

// SetAcknowledgedBy sets the value of AcknowledgedBy.
func (s *Alert) SetAcknowledgedBy(val OptNilUUID) {
	s.AcknowledgedBy = val
}

// SetResolvedAt sets the value of ResolvedAt.
func (s *Alert) SetResolvedAt(val OptNilDateTime) {
	s.ResolvedAt = val
}

// SetResolvedBy sets the value of ResolvedBy.
func (s *Alert) SetResolvedBy(val OptNilUUID) {
	s.ResolvedBy = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Alert) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// Single alert response wrapper.
// Ref: #/components/schemas/AlertResponse
type AlertResponse struct {
	Data Alert `json:"data"`
}

// GetData returns the value of Data.
func (s *AlertResponse) GetData() Alert {
	return s.Data
}

// SetData sets the value of Data.
func (s *AlertResponse) SetData(val Alert) {
	s.Data = val
}

func (*AlertResponse) acknowledgeAlertRes() {}
func (*AlertResponse) createAlertRes()      {}
func (*AlertResponse) getAlertRes()         {}
func (*AlertResponse) resolveAlertRes()     {}

// Alert severity level.
// Ref: #/components/schemas/AlertSeverity
type AlertSeverity string

const (
	AlertSeverityInfo     AlertSeverity = "info"
	AlertSeverityWarning  AlertSeverity = "warning"
	AlertSeverityCritical AlertSeverity = "critical"
)

// AllValues returns all AlertSeverity values.
func (AlertSeverity) AllValues() []AlertSeverity {
	return []AlertSeverity{
		AlertSeverityInfo,
		AlertSeverityWarning,
		AlertSeverityCritical,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s AlertSeverity) MarshalText() ([]byte, error) {
	switch s {
	case AlertSeverityInfo:
		return []byte(s), nil
	case AlertSeverityWarning:
		return []byte(s), nil
	case AlertSeverityCritical:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *AlertSeverity) UnmarshalText(data []byte) error {
	switch AlertSeverity(data) {
	case AlertSeverityInfo:
		*s = AlertSeverityInfo
		return nil
	case AlertSeverityWarning:
		*s = AlertSeverityWarning
		return nil
	case AlertSeverityCritical:
		*s = AlertSeverityCritical
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Alert status.
// Ref: #/components/schemas/AlertStatus
type AlertStatus string

const (
	AlertStatusOpen         AlertStatus = "open"
	AlertStatusAcknowledged AlertStatus = "acknowledged"
	AlertStatusResolved     AlertStatus = "resolved"
)

// AllValues returns all AlertStatus values.
func (AlertStatus) AllValues() []AlertStatus {
	return []AlertStatus{
		AlertStatusOpen,
		AlertStatusAcknowledged,
		AlertStatusResolved,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s AlertStatus) MarshalText() ([]byte, error) {
	switch s {
	case AlertStatusOpen:
		return []byte(s), nil
	case AlertStatusAcknowledged:
		return []byte(s), nil
	case AlertStatusResolved:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *AlertStatus) UnmarshalText(data []byte) error {
	switch AlertStatus(data) {
	case AlertStatusOpen:
		*s = AlertStatusOpen
		return nil
	case AlertStatusAcknowledged:
		*s = AlertStatusAcknowledged
		return nil
	case AlertStatusResolved:
		*s = AlertStatusResolved
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type AlertStatusQuery string

const (
	AlertStatusQueryOpen         AlertStatusQuery = "open"
	AlertStatusQueryAcknowledged AlertStatusQuery = "acknowledged"
	AlertStatusQueryResolved     AlertStatusQuery = "resolved"
)

// AllValues returns all AlertStatusQuery values.
func (AlertStatusQuery) AllValues() []AlertStatusQuery {
	return []AlertStatusQuery{
		AlertStatusQueryOpen,
		AlertStatusQueryAcknowledged,
		AlertStatusQueryResolved,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s AlertStatusQuery) MarshalText() ([]byte, error) {
	switch s {
	case AlertStatusQueryOpen:
		return []byte(s), nil
	case AlertStatusQueryAcknowledged:
		return []byte(s), nil
	case AlertStatusQueryResolved:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *AlertStatusQuery) UnmarshalText(data []byte) error {
	switch AlertStatusQuery(data) {
	case AlertStatusQueryOpen:
		*s = AlertStatusQueryOpen
		return nil
	case AlertStatusQueryAcknowledged:
		*s = AlertStatusQueryAcknowledged
		return nil
	case AlertStatusQueryResolved:
		*s = AlertStatusQueryResolved
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Audit log entry for tracking changes.
// Ref: #/components/schemas/AuditLog
type AuditLog struct {
	// Unique audit log identifier.
	ID uuid.UUID `json:"id"`
	// Tenant identifier.
	TenantID uuid.UUID `json:"tenant_id"`
	// User who performed the action.
	UserID OptNilUUID `json:"user_id"`
	// Type of event.
	EventType string `json:"event_type"`
	// Type of resource affected.
	ResourceType string `json:"resource_type"`
	// ID of the affected resource.
	ResourceID OptNilUUID `json:"resource_id"`
	// Action performed.
	Action string `json:"action"`
	// Previous state of the resource.
	OldValue OptNilAuditLogOldValue `json:"old_value"`
	// New state of the resource.
	NewValue OptNilAuditLogNewValue `json:"new_value"`
	// Client IP address.
	IPAddress OptNilString `json:"ip_address"`
	// Client user agent.
	UserAgent OptNilString `json:"user_agent"`
	// When the event occurred.
	CreatedAt time.Time `json:"created_at"`
}

// GetID returns the value of ID.
func (s *AuditLog) GetID() uuid.UUID {
	return s.ID
}

// GetTenantID returns the value of TenantID.
func (s *AuditLog) GetTenantID() uuid.UUID {
	return s.TenantID
}

// GetUserID returns the value of UserID.
func (s *AuditLog) GetUserID() OptNilUUID {
	return s.UserID
}

// GetEventType returns the value of EventType.
func (s *AuditLog) GetEventType() string {
	return s.EventType
}

// GetResourceType returns the value of ResourceType.
func (s *AuditLog) GetResourceType() string {
	return s.ResourceType
}

// GetResourceID returns the value of ResourceID.
func (s *AuditLog) GetResourceID() OptNilUUID {
	return s.ResourceID
}

// GetAction returns the value of Action.
func (s *AuditLog) GetAction() string {
	return s.Action
}

// GetOldValue returns the value of OldValue.
func (s *AuditLog) GetOldValue() OptNilAuditLogOldValue {
	return s.OldValue
}

// GetNewValue returns the value of NewValue.
func (s *AuditLog) GetNewValue() OptNilAuditLogNewValue {
	return s.NewValue
}

// GetIPAddress returns the value of IPAddress.
func (s *AuditLog) GetIPAddress() OptNilString {
	return s.IPAddress
}

// GetUserAgent returns the value of UserAgent.
func (s *AuditLog) GetUserAgent() OptNilString {
	return s.UserAgent
}

// GetCreatedAt returns the value of CreatedAt.
func (s *AuditLog) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// SetID sets the value of ID.
func (s *AuditLog) SetID(val uuid.UUID) {
	s.ID = val
}

// SetTenantID sets the value of TenantID.
func (s *AuditLog) SetTenantID(val uuid.UUID) {
	s.TenantID = val
}

// SetUserID sets the value of UserID.
func (s *AuditLog) SetUserID(val OptNilUUID) {
	s.UserID = val
}

// SetEventType sets the value of EventType.
func (s *AuditLog) SetEventType(val string) {
	s.EventType = val
}

// SetResourceType sets the value of ResourceType.
func (s *AuditLog) SetResourceType(val string) {
	s.ResourceType = val
}

// SetResourceID sets the value of ResourceID.
func (s *AuditLog) SetResourceID(val OptNilUUID) {
	s.ResourceID = val
}

// SetAction sets the value of Action.
func (s *AuditLog) SetAction(val string) {
	s.Action = val
}

// SetOldValue sets the value of OldValue.
func (s *AuditLog) SetOldValue(val OptNilAuditLogOldValue) {
	s.OldValue = val
}

// SetNewValue sets the value of NewValue.
func (s *AuditLog) SetNewValue(val OptNilAuditLogNewValue) {
	s.NewValue = val
}

// SetIPAddress sets the value of IPAddress.
func (s *AuditLog) SetIPAddress(val OptNilString) {
	s.IPAddress = val
}

// SetUserAgent sets the value of UserAgent.
func (s *AuditLog) SetUserAgent(val OptNilString) {
	s.UserAgent = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *AuditLog) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// New state of the resource.
type AuditLogNewValue map[string]jx.Raw

func (s *AuditLogNewValue) init() AuditLogNewValue {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

// Previous state of the resource.
type AuditLogOldValue map[string]jx.Raw

func (s *AuditLogOldValue) init() AuditLogOldValue {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

type BearerAuth struct {
	Token string
	Roles []string
}

// GetToken returns the value of Token.
func (s *BearerAuth) GetToken() string {
	return s.Token
}

// GetRoles returns the value of Roles.
func (s *BearerAuth) GetRoles() []string {
	return s.Roles
}

// SetToken sets the value of Token.
func (s *BearerAuth) SetToken(val string) {
	s.Token = val
}

// SetRoles sets the value of Roles.
func (s *BearerAuth) SetRoles(val []string) {
	s.Roles = val
}

type CancelExecutionInternalServerError Error

func (*CancelExecutionInternalServerError) cancelExecutionRes() {}

type CancelExecutionNotFound Error

func (*CancelExecutionNotFound) cancelExecutionRes() {}

type CancelExecutionUnauthorized Error

func (*CancelExecutionUnauthorized) cancelExecutionRes() {}

type CancelExecutionUnprocessableEntity Error

func (*CancelExecutionUnprocessableEntity) cancelExecutionRes() {}

type CreateAlertBadRequest Error

func (*CreateAlertBadRequest) createAlertRes() {}

type CreateAlertInternalServerError Error

func (*CreateAlertInternalServerError) createAlertRes() {}

// Request body for creating an alert.
// Ref: #/components/schemas/CreateAlertRequest
type CreateAlertRequest struct {
	// Related workflow.
	WorkflowID OptUUID `json:"workflow_id"`
	// Related execution.
	ExecutionID OptUUID       `json:"execution_id"`
	Severity    AlertSeverity `json:"severity"`
	Title       string        `json:"title"`
	// Detailed message.
	Message OptString `json:"message"`
}

// GetWorkflowID returns the value of WorkflowID.
func (s *CreateAlertRequest) GetWorkflowID() OptUUID {
	return s.WorkflowID
}

// GetExecutionID returns the value of ExecutionID.
func (s *CreateAlertRequest) GetExecutionID() OptUUID {
	return s.ExecutionID
}

// GetSeverity returns the value of Severity.
func (s *CreateAlertRequest) GetSeverity() AlertSeverity {
	return s.Severity
}

// GetTitle returns the value of Title.
func (s *CreateAlertRequest) GetTitle() string {
	return s.Title
}

// GetMessage returns the value of Message.
func (s *CreateAlertRequest) GetMessage() OptString {
	return s.Message
}

// SetWorkflowID sets the value of WorkflowID.
func (s *CreateAlertRequest) SetWorkflowID(val OptUUID) {
	s.WorkflowID = val
}

// SetExecutionID sets the value of ExecutionID.
func (s *CreateAlertRequest) SetExecutionID(val OptUUID) {
	s.ExecutionID = val
}

// SetSeverity sets the value of Severity.
func (s *CreateAlertRequest) SetSeverity(val AlertSeverity) {
	s.Severity = val
}

// SetTitle sets the value of Title.
func (s *CreateAlertRequest) SetTitle(val string) {
	s.Title = val
}

// SetMessage sets the value of Message.
func (s *CreateAlertRequest) SetMessage(val OptString) {
	s.Message = val
}

type CreateAlertUnauthorized Error

func (*CreateAlertUnauthorized) createAlertRes() {}

type CreateWorkflowBadRequest Error

func (*CreateWorkflowBadRequest) createWorkflowRes() {}

type CreateWorkflowConflict Error

func (*CreateWorkflowConflict) createWorkflowRes() {}

type CreateWorkflowInternalServerError Error

func (*CreateWorkflowInternalServerError) createWorkflowRes() {}

// Request body for creating a workflow.
// Ref: #/components/schemas/CreateWorkflowRequest
type CreateWorkflowRequest struct {
	// Workflow name.
	Name string `json:"name"`
	// Optional description.
	Description OptString `json:"description"`
	// Workflow definition.
	Definition CreateWorkflowRequestDefinition `json:"definition"`
	// Optional cron schedule.
	Schedule OptString `json:"schedule"`
}

// GetName returns the value of Name.
func (s *CreateWorkflowRequest) GetName() string {
	return s.Name
}

// GetDescription returns the value of Description.
func (s *CreateWorkflowRequest) GetDescription() OptString {
	return s.Description
}

// GetDefinition returns the value of Definition.
func (s *CreateWorkflowRequest) GetDefinition() CreateWorkflowRequestDefinition {
	return s.Definition
}

// GetSchedule returns the value of Schedule.
func (s *CreateWorkflowRequest) GetSchedule() OptString {
	return s.Schedule
}

// SetName sets the value of Name.
func (s *CreateWorkflowRequest) SetName(val string) {
	s.Name = val
}

// SetDescription sets the value of Description.
func (s *CreateWorkflowRequest) SetDescription(val OptString) {
	s.Description = val
}

// SetDefinition sets the value of Definition.
func (s *CreateWorkflowRequest) SetDefinition(val CreateWorkflowRequestDefinition) {
	s.Definition = val
}

// SetSchedule sets the value of Schedule.
func (s *CreateWorkflowRequest) SetSchedule(val OptString) {
	s.Schedule = val
}

// Workflow definition.
type CreateWorkflowRequestDefinition map[string]jx.Raw

func (s *CreateWorkflowRequestDefinition) init() CreateWorkflowRequestDefinition {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

type CreateWorkflowUnauthorized Error

func (*CreateWorkflowUnauthorized) createWorkflowRes() {}

type DeleteWorkflowInternalServerError Error

func (*DeleteWorkflowInternalServerError) deleteWorkflowRes() {}

type DeleteWorkflowNotFound Error

func (*DeleteWorkflowNotFound) deleteWorkflowRes() {}

type DeleteWorkflowUnauthorized Error

func (*DeleteWorkflowUnauthorized) deleteWorkflowRes() {}

// Error response.
// Ref: #/components/schemas/Error
type Error struct {
	// Error code.
	Code string `json:"code"`
	// Human-readable error message.
	Message string `json:"message"`
	// Additional error details.
	Details OptErrorDetails `json:"details"`
}

// GetCode returns the value of Code.
func (s *Error) GetCode() string {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *Error) GetMessage() string {
	return s.Message
}

// GetDetails returns the value of Details.
func (s *Error) GetDetails() OptErrorDetails {
	return s.Details
}

// SetCode sets the value of Code.
func (s *Error) SetCode(val string) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *Error) SetMessage(val string) {
	s.Message = val
}

// SetDetails sets the value of Details.
func (s *Error) SetDetails(val OptErrorDetails) {
	s.Details = val
}

// Additional error details.
type ErrorDetails map[string]jx.Raw

func (s *ErrorDetails) init() ErrorDetails {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

type ExecuteWorkflowBadRequest Error

func (*ExecuteWorkflowBadRequest) executeWorkflowRes() {}

type ExecuteWorkflowInternalServerError Error

func (*ExecuteWorkflowInternalServerError) executeWorkflowRes() {}

type ExecuteWorkflowNotFound Error

func (*ExecuteWorkflowNotFound) executeWorkflowRes() {}

// Request body for executing a workflow.
// Ref: #/components/schemas/ExecuteWorkflowRequest
type ExecuteWorkflowRequest struct {
	// Input data for the workflow execution.
	Input OptExecuteWorkflowRequestInput `json:"input"`
}

// GetInput returns the value of Input.
func (s *ExecuteWorkflowRequest) GetInput() OptExecuteWorkflowRequestInput {
	return s.Input
}

// SetInput sets the value of Input.
func (s *ExecuteWorkflowRequest) SetInput(val OptExecuteWorkflowRequestInput) {
	s.Input = val
}

// Input data for the workflow execution.
type ExecuteWorkflowRequestInput map[string]jx.Raw

func (s *ExecuteWorkflowRequestInput) init() ExecuteWorkflowRequestInput {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

type ExecuteWorkflowUnauthorized Error

func (*ExecuteWorkflowUnauthorized) executeWorkflowRes() {}

type ExecuteWorkflowUnprocessableEntity Error

func (*ExecuteWorkflowUnprocessableEntity) executeWorkflowRes() {}

// Workflow execution instance.
// Ref: #/components/schemas/Execution
type Execution struct {
	// Unique execution identifier.
	ID uuid.UUID `json:"id"`
	// Tenant identifier.
	TenantID uuid.UUID `json:"tenant_id"`
	// Parent workflow identifier.
	WorkflowID uuid.UUID `json:"workflow_id"`
	// Temporal workflow ID.
	TemporalWorkflowID OptString `json:"temporal_workflow_id"`
	// Temporal run ID.
	TemporalRunID OptString       `json:"temporal_run_id"`
	Status        ExecutionStatus `json:"status"`
	// Input data provided at execution.
	Input OptExecutionInput `json:"input"`
	// Output data from execution.
	Output OptExecutionOutput `json:"output"`
	// Error message if execution failed.
	Error OptString `json:"error"`
	// Execution start time.
	StartedAt OptDateTime `json:"started_at"`
	// Execution completion time.
	CompletedAt OptDateTime `json:"completed_at"`
	// User who triggered the execution.
	CreatedBy OptUUID `json:"created_by"`
	// Creation timestamp.
	CreatedAt time.Time `json:"created_at"`
}

// GetID returns the value of ID.
func (s *Execution) GetID() uuid.UUID {
	return s.ID
}

// GetTenantID returns the value of TenantID.
func (s *Execution) GetTenantID() uuid.UUID {
	return s.TenantID
}

// GetWorkflowID returns the value of WorkflowID.
func (s *Execution) GetWorkflowID() uuid.UUID {
	return s.WorkflowID
}

// GetTemporalWorkflowID returns the value of TemporalWorkflowID.
func (s *Execution) GetTemporalWorkflowID() OptString {
	return s.TemporalWorkflowID
}

// GetTemporalRunID returns the value of TemporalRunID.
func (s *Execution) GetTemporalRunID() OptString {
	return s.TemporalRunID
}

// GetStatus returns the value of Status.
func (s *Execution) GetStatus() ExecutionStatus {
	return s.Status
}

// GetInput returns the value of Input.
func (s *Execution) GetInput() OptExecutionInput {
	return s.Input
}

// GetOutput returns the value of Output.
func (s *Execution) GetOutput() OptExecutionOutput {
	return s.Output
}

// GetError returns the value of Error.
func (s *Execution) GetError() OptString {
	return s.Error
}

// GetStartedAt returns the value of StartedAt.
func (s *Execution) GetStartedAt() OptDateTime {
	return s.StartedAt
}

// GetCompletedAt returns the value of CompletedAt.
func (s *Execution) GetCompletedAt() OptDateTime {
	return s.CompletedAt
}

// GetCreatedBy returns the value of CreatedBy.
func (s *Execution) GetCreatedBy() OptUUID {
	return s.CreatedBy
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Execution) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// SetID sets the value of ID.
func (s *Execution) SetID(val uuid.UUID) {
	s.ID = val
}

// SetTenantID sets the value of TenantID.
func (s *Execution) SetTenantID(val uuid.UUID) {
	s.TenantID = val
}

// SetWorkflowID sets the value of WorkflowID.
func (s *Execution) SetWorkflowID(val uuid.UUID) {
	s.WorkflowID = val
}

// SetTemporalWorkflowID sets the value of TemporalWorkflowID.
func (s *Execution) SetTemporalWorkflowID(val OptString) {
	s.TemporalWorkflowID = val
}

// SetTemporalRunID sets the value of TemporalRunID.
func (s *Execution) SetTemporalRunID(val OptString) {
	s.TemporalRunID = val
}

// SetStatus sets the value of Status.
func (s *Execution) SetStatus(val ExecutionStatus) {
	s.Status = val
}

// SetInput sets the value of Input.
func (s *Execution) SetInput(val OptExecutionInput) {
	s.Input = val
}

// SetOutput sets the value of Output.
func (s *Execution) SetOutput(val OptExecutionOutput) {
	s.Output = val
}

// SetError sets the value of Error.
func (s *Execution) SetError(val OptString) {
	s.Error = val
}

// SetStartedAt sets the value of StartedAt.
func (s *Execution) SetStartedAt(val OptDateTime) {
	s.StartedAt = val
}

// SetCompletedAt sets the value of CompletedAt.
func (s *Execution) SetCompletedAt(val OptDateTime) {
	s.CompletedAt = val
}

// SetCreatedBy sets the value of CreatedBy.
func (s *Execution) SetCreatedBy(val OptUUID) {
	s.CreatedBy = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Execution) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// Input data provided at execution.
type ExecutionInput map[string]jx.Raw

func (s *ExecutionInput) init() ExecutionInput {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

// Output data from execution.
type ExecutionOutput map[string]jx.Raw

func (s *ExecutionOutput) init() ExecutionOutput {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

// Single execution response wrapper.
// Ref: #/components/schemas/ExecutionResponse
type ExecutionResponse struct {
	Data Execution `json:"data"`
}

// GetData returns the value of Data.
func (s *ExecutionResponse) GetData() Execution {
	return s.Data
}

// SetData sets the value of Data.
func (s *ExecutionResponse) SetData(val Execution) {
	s.Data = val
}

func (*ExecutionResponse) cancelExecutionRes() {}
func (*ExecutionResponse) executeWorkflowRes() {}
func (*ExecutionResponse) getExecutionRes()    {}

// Execution status.
// Ref: #/components/schemas/ExecutionStatus
type ExecutionStatus string

const (
	ExecutionStatusPending   ExecutionStatus = "pending"
	ExecutionStatusRunning   ExecutionStatus = "running"
	ExecutionStatusCompleted ExecutionStatus = "completed"
	ExecutionStatusFailed    ExecutionStatus = "failed"
	ExecutionStatusCancelled ExecutionStatus = "cancelled"
)

// AllValues returns all ExecutionStatus values.
func (ExecutionStatus) AllValues() []ExecutionStatus {
	return []ExecutionStatus{
		ExecutionStatusPending,
		ExecutionStatusRunning,
		ExecutionStatusCompleted,
		ExecutionStatusFailed,
		ExecutionStatusCancelled,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ExecutionStatus) MarshalText() ([]byte, error) {
	switch s {
	case ExecutionStatusPending:
		return []byte(s), nil
	case ExecutionStatusRunning:
		return []byte(s), nil
	case ExecutionStatusCompleted:
		return []byte(s), nil
	case ExecutionStatusFailed:
		return []byte(s), nil
	case ExecutionStatusCancelled:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ExecutionStatus) UnmarshalText(data []byte) error {
	switch ExecutionStatus(data) {
	case ExecutionStatusPending:
		*s = ExecutionStatusPending
		return nil
	case ExecutionStatusRunning:
		*s = ExecutionStatusRunning
		return nil
	case ExecutionStatusCompleted:
		*s = ExecutionStatusCompleted
		return nil
	case ExecutionStatusFailed:
		*s = ExecutionStatusFailed
		return nil
	case ExecutionStatusCancelled:
		*s = ExecutionStatusCancelled
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type ExecutionStatusQuery string

const (
	ExecutionStatusQueryPending   ExecutionStatusQuery = "pending"
	ExecutionStatusQueryRunning   ExecutionStatusQuery = "running"
	ExecutionStatusQueryCompleted ExecutionStatusQuery = "completed"
	ExecutionStatusQueryFailed    ExecutionStatusQuery = "failed"
	ExecutionStatusQueryCancelled ExecutionStatusQuery = "cancelled"
)

// AllValues returns all ExecutionStatusQuery values.
func (ExecutionStatusQuery) AllValues() []ExecutionStatusQuery {
	return []ExecutionStatusQuery{
		ExecutionStatusQueryPending,
		ExecutionStatusQueryRunning,
		ExecutionStatusQueryCompleted,
		ExecutionStatusQueryFailed,
		ExecutionStatusQueryCancelled,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ExecutionStatusQuery) MarshalText() ([]byte, error) {
	switch s {
	case ExecutionStatusQueryPending:
		return []byte(s), nil
	case ExecutionStatusQueryRunning:
		return []byte(s), nil
	case ExecutionStatusQueryCompleted:
		return []byte(s), nil
	case ExecutionStatusQueryFailed:
		return []byte(s), nil
	case ExecutionStatusQueryCancelled:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ExecutionStatusQuery) UnmarshalText(data []byte) error {
	switch ExecutionStatusQuery(data) {
	case ExecutionStatusQueryPending:
		*s = ExecutionStatusQueryPending
		return nil
	case ExecutionStatusQueryRunning:
		*s = ExecutionStatusQueryRunning
		return nil
	case ExecutionStatusQueryCompleted:
		*s = ExecutionStatusQueryCompleted
		return nil
	case ExecutionStatusQueryFailed:
		*s = ExecutionStatusQueryFailed
		return nil
	case ExecutionStatusQueryCancelled:
		*s = ExecutionStatusQueryCancelled
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type GetAlertInternalServerError Error

func (*GetAlertInternalServerError) getAlertRes() {}

type GetAlertNotFound Error

func (*GetAlertNotFound) getAlertRes() {}

type GetAlertUnauthorized Error

func (*GetAlertUnauthorized) getAlertRes() {}

type GetExecutionInternalServerError Error

func (*GetExecutionInternalServerError) getExecutionRes() {}

type GetExecutionNotFound Error

func (*GetExecutionNotFound) getExecutionRes() {}

type GetExecutionUnauthorized Error

func (*GetExecutionUnauthorized) getExecutionRes() {}

type GetWorkflowInternalServerError Error

func (*GetWorkflowInternalServerError) getWorkflowRes() {}

type GetWorkflowNotFound Error

func (*GetWorkflowNotFound) getWorkflowRes() {}

type GetWorkflowUnauthorized Error

func (*GetWorkflowUnauthorized) getWorkflowRes() {}

type HealthCheckOK HealthStatus

func (*HealthCheckOK) healthCheckRes() {}

type HealthCheckServiceUnavailable HealthStatus

func (*HealthCheckServiceUnavailable) healthCheckRes() {}

// Health check response.
// Ref: #/components/schemas/HealthStatus
type HealthStatus struct {
	Status HealthStatusStatus `json:"status"`
	// Individual health checks.
	Checks OptHealthStatusChecks `json:"checks"`
}

// GetStatus returns the value of Status.
func (s *HealthStatus) GetStatus() HealthStatusStatus {
	return s.Status
}

// GetChecks returns the value of Checks.
func (s *HealthStatus) GetChecks() OptHealthStatusChecks {
	return s.Checks
}

// SetStatus sets the value of Status.
func (s *HealthStatus) SetStatus(val HealthStatusStatus) {
	s.Status = val
}

// SetChecks sets the value of Checks.
func (s *HealthStatus) SetChecks(val OptHealthStatusChecks) {
	s.Checks = val
}

// Individual health checks.
type HealthStatusChecks map[string]HealthStatusChecksItem

func (s *HealthStatusChecks) init() HealthStatusChecks {
	m := *s
	if m == nil {
		m = map[string]HealthStatusChecksItem{}
		*s = m
	}
	return m
}

type HealthStatusChecksItem struct {
	Status  OptString `json:"status"`
	Message OptString `json:"message"`
}

// GetStatus returns the value of Status.
func (s *HealthStatusChecksItem) GetStatus() OptString {
	return s.Status
}

// GetMessage returns the value of Message.
func (s *HealthStatusChecksItem) GetMessage() OptString {
	return s.Message
}

// SetStatus sets the value of Status.
func (s *HealthStatusChecksItem) SetStatus(val OptString) {
	s.Status = val
}

// SetMessage sets the value of Message.
func (s *HealthStatusChecksItem) SetMessage(val OptString) {
	s.Message = val
}

type HealthStatusStatus string

const (
	HealthStatusStatusHealthy   HealthStatusStatus = "healthy"
	HealthStatusStatusUnhealthy HealthStatusStatus = "unhealthy"
	HealthStatusStatusDegraded  HealthStatusStatus = "degraded"
)

// AllValues returns all HealthStatusStatus values.
func (HealthStatusStatus) AllValues() []HealthStatusStatus {
	return []HealthStatusStatus{
		HealthStatusStatusHealthy,
		HealthStatusStatusUnhealthy,
		HealthStatusStatusDegraded,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s HealthStatusStatus) MarshalText() ([]byte, error) {
	switch s {
	case HealthStatusStatusHealthy:
		return []byte(s), nil
	case HealthStatusStatusUnhealthy:
		return []byte(s), nil
	case HealthStatusStatusDegraded:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *HealthStatusStatus) UnmarshalText(data []byte) error {
	switch HealthStatusStatus(data) {
	case HealthStatusStatusHealthy:
		*s = HealthStatusStatusHealthy
		return nil
	case HealthStatusStatusUnhealthy:
		*s = HealthStatusStatusUnhealthy
		return nil
	case HealthStatusStatusDegraded:
		*s = HealthStatusStatusDegraded
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type ListAlertsInternalServerError Error

func (*ListAlertsInternalServerError) listAlertsRes() {}

type ListAlertsSeverity string

const (
	ListAlertsSeverityInfo     ListAlertsSeverity = "info"
	ListAlertsSeverityWarning  ListAlertsSeverity = "warning"
	ListAlertsSeverityCritical ListAlertsSeverity = "critical"
)

// AllValues returns all ListAlertsSeverity values.
func (ListAlertsSeverity) AllValues() []ListAlertsSeverity {
	return []ListAlertsSeverity{
		ListAlertsSeverityInfo,
		ListAlertsSeverityWarning,
		ListAlertsSeverityCritical,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ListAlertsSeverity) MarshalText() ([]byte, error) {
	switch s {
	case ListAlertsSeverityInfo:
		return []byte(s), nil
	case ListAlertsSeverityWarning:
		return []byte(s), nil
	case ListAlertsSeverityCritical:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ListAlertsSeverity) UnmarshalText(data []byte) error {
	switch ListAlertsSeverity(data) {
	case ListAlertsSeverityInfo:
		*s = ListAlertsSeverityInfo
		return nil
	case ListAlertsSeverityWarning:
		*s = ListAlertsSeverityWarning
		return nil
	case ListAlertsSeverityCritical:
		*s = ListAlertsSeverityCritical
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type ListAlertsUnauthorized Error

func (*ListAlertsUnauthorized) listAlertsRes() {}

type ListAuditLogsAction string

const (
	ListAuditLogsActionCreate      ListAuditLogsAction = "create"
	ListAuditLogsActionUpdate      ListAuditLogsAction = "update"
	ListAuditLogsActionDelete      ListAuditLogsAction = "delete"
	ListAuditLogsActionExecute     ListAuditLogsAction = "execute"
	ListAuditLogsActionCancel      ListAuditLogsAction = "cancel"
	ListAuditLogsActionAcknowledge ListAuditLogsAction = "acknowledge"
	ListAuditLogsActionResolve     ListAuditLogsAction = "resolve"
)

// AllValues returns all ListAuditLogsAction values.
func (ListAuditLogsAction) AllValues() []ListAuditLogsAction {
	return []ListAuditLogsAction{
		ListAuditLogsActionCreate,
		ListAuditLogsActionUpdate,
		ListAuditLogsActionDelete,
		ListAuditLogsActionExecute,
		ListAuditLogsActionCancel,
		ListAuditLogsActionAcknowledge,
		ListAuditLogsActionResolve,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ListAuditLogsAction) MarshalText() ([]byte, error) {
	switch s {
	case ListAuditLogsActionCreate:
		return []byte(s), nil
	case ListAuditLogsActionUpdate:
		return []byte(s), nil
	case ListAuditLogsActionDelete:
		return []byte(s), nil
	case ListAuditLogsActionExecute:
		return []byte(s), nil
	case ListAuditLogsActionCancel:
		return []byte(s), nil
	case ListAuditLogsActionAcknowledge:
		return []byte(s), nil
	case ListAuditLogsActionResolve:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ListAuditLogsAction) UnmarshalText(data []byte) error {
	switch ListAuditLogsAction(data) {
	case ListAuditLogsActionCreate:
		*s = ListAuditLogsActionCreate
		return nil
	case ListAuditLogsActionUpdate:
		*s = ListAuditLogsActionUpdate
		return nil
	case ListAuditLogsActionDelete:
		*s = ListAuditLogsActionDelete
		return nil
	case ListAuditLogsActionExecute:
		*s = ListAuditLogsActionExecute
		return nil
	case ListAuditLogsActionCancel:
		*s = ListAuditLogsActionCancel
		return nil
	case ListAuditLogsActionAcknowledge:
		*s = ListAuditLogsActionAcknowledge
		return nil
	case ListAuditLogsActionResolve:
		*s = ListAuditLogsActionResolve
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type ListAuditLogsByResourceInternalServerError Error

func (*ListAuditLogsByResourceInternalServerError) listAuditLogsByResourceRes() {}

type ListAuditLogsByResourceNotFound Error

func (*ListAuditLogsByResourceNotFound) listAuditLogsByResourceRes() {}

type ListAuditLogsByResourceUnauthorized Error

func (*ListAuditLogsByResourceUnauthorized) listAuditLogsByResourceRes() {}

type ListAuditLogsByUserInternalServerError Error

func (*ListAuditLogsByUserInternalServerError) listAuditLogsByUserRes() {}

type ListAuditLogsByUserNotFound Error

func (*ListAuditLogsByUserNotFound) listAuditLogsByUserRes() {}

type ListAuditLogsByUserUnauthorized Error

func (*ListAuditLogsByUserUnauthorized) listAuditLogsByUserRes() {}

type ListAuditLogsInternalServerError Error

func (*ListAuditLogsInternalServerError) listAuditLogsRes() {}

type ListAuditLogsResourceType string

const (
	ListAuditLogsResourceTypeWorkflow  ListAuditLogsResourceType = "workflow"
	ListAuditLogsResourceTypeExecution ListAuditLogsResourceType = "execution"
	ListAuditLogsResourceTypeAlert     ListAuditLogsResourceType = "alert"
)

// AllValues returns all ListAuditLogsResourceType values.
func (ListAuditLogsResourceType) AllValues() []ListAuditLogsResourceType {
	return []ListAuditLogsResourceType{
		ListAuditLogsResourceTypeWorkflow,
		ListAuditLogsResourceTypeExecution,
		ListAuditLogsResourceTypeAlert,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ListAuditLogsResourceType) MarshalText() ([]byte, error) {
	switch s {
	case ListAuditLogsResourceTypeWorkflow:
		return []byte(s), nil
	case ListAuditLogsResourceTypeExecution:
		return []byte(s), nil
	case ListAuditLogsResourceTypeAlert:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ListAuditLogsResourceType) UnmarshalText(data []byte) error {
	switch ListAuditLogsResourceType(data) {
	case ListAuditLogsResourceTypeWorkflow:
		*s = ListAuditLogsResourceTypeWorkflow
		return nil
	case ListAuditLogsResourceTypeExecution:
		*s = ListAuditLogsResourceTypeExecution
		return nil
	case ListAuditLogsResourceTypeAlert:
		*s = ListAuditLogsResourceTypeAlert
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type ListAuditLogsUnauthorized Error

func (*ListAuditLogsUnauthorized) listAuditLogsRes() {}

type ListExecutionsInternalServerError Error

func (*ListExecutionsInternalServerError) listExecutionsRes() {}

type ListExecutionsUnauthorized Error

func (*ListExecutionsUnauthorized) listExecutionsRes() {}

type ListWorkflowExecutionsInternalServerError Error

func (*ListWorkflowExecutionsInternalServerError) listWorkflowExecutionsRes() {}

type ListWorkflowExecutionsNotFound Error

func (*ListWorkflowExecutionsNotFound) listWorkflowExecutionsRes() {}

type ListWorkflowExecutionsUnauthorized Error

func (*ListWorkflowExecutionsUnauthorized) listWorkflowExecutionsRes() {}

type ListWorkflowsInternalServerError Error

func (*ListWorkflowsInternalServerError) listWorkflowsRes() {}

type ListWorkflowsUnauthorized Error

func (*ListWorkflowsUnauthorized) listWorkflowsRes() {}

type LivenessProbeOK HealthStatus

func (*LivenessProbeOK) livenessProbeRes() {}

type LivenessProbeServiceUnavailable HealthStatus

func (*LivenessProbeServiceUnavailable) livenessProbeRes() {}

// Ref: #/components/responses/NoContent
type NoContent struct{}

func (*NoContent) deleteWorkflowRes() {}

// NewOptAlertStatusQuery returns new OptAlertStatusQuery with value set to v.
func NewOptAlertStatusQuery(v AlertStatusQuery) OptAlertStatusQuery {
	return OptAlertStatusQuery{
		Value: v,
		Set:   true,
	}
}

// OptAlertStatusQuery is optional AlertStatusQuery.
type OptAlertStatusQuery struct {
	Value AlertStatusQuery
	Set   bool
}

// IsSet returns true if OptAlertStatusQuery was set.
func (o OptAlertStatusQuery) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptAlertStatusQuery) Reset() {
	var v AlertStatusQuery
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptAlertStatusQuery) SetTo(v AlertStatusQuery) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptAlertStatusQuery) Get() (v AlertStatusQuery, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptAlertStatusQuery) Or(d AlertStatusQuery) AlertStatusQuery {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptDateTime returns new OptDateTime with value set to v.
func NewOptDateTime(v time.Time) OptDateTime {
	return OptDateTime{
		Value: v,
		Set:   true,
	}
}

// OptDateTime is optional time.Time.
type OptDateTime struct {
	Value time.Time
	Set   bool
}

// IsSet returns true if OptDateTime was set.
func (o OptDateTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDateTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDateTime) SetTo(v time.Time) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDateTime) Get() (v time.Time, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptErrorDetails returns new OptErrorDetails with value set to v.
func NewOptErrorDetails(v ErrorDetails) OptErrorDetails {
	return OptErrorDetails{
		Value: v,
		Set:   true,
	}
}

// OptErrorDetails is optional ErrorDetails.
type OptErrorDetails struct {
	Value ErrorDetails
	Set   bool
}

// IsSet returns true if OptErrorDetails was set.
func (o OptErrorDetails) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptErrorDetails) Reset() {
	var v ErrorDetails
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptErrorDetails) SetTo(v ErrorDetails) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptErrorDetails) Get() (v ErrorDetails, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptErrorDetails) Or(d ErrorDetails) ErrorDetails {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptExecuteWorkflowRequest returns new OptExecuteWorkflowRequest with value set to v.
func NewOptExecuteWorkflowRequest(v ExecuteWorkflowRequest) OptExecuteWorkflowRequest {
	return OptExecuteWorkflowRequest{
		Value: v,
		Set:   true,
	}
}

// OptExecuteWorkflowRequest is optional ExecuteWorkflowRequest.
type OptExecuteWorkflowRequest struct {
	Value ExecuteWorkflowRequest
	Set   bool
}

// IsSet returns true if OptExecuteWorkflowRequest was set.
func (o OptExecuteWorkflowRequest) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptExecuteWorkflowRequest) Reset() {
	var v ExecuteWorkflowRequest
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptExecuteWorkflowRequest) SetTo(v ExecuteWorkflowRequest) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptExecuteWorkflowRequest) Get() (v ExecuteWorkflowRequest, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptExecuteWorkflowRequest) Or(d ExecuteWorkflowRequest) ExecuteWorkflowRequest {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptExecuteWorkflowRequestInput returns new OptExecuteWorkflowRequestInput with value set to v.
func NewOptExecuteWorkflowRequestInput(v ExecuteWorkflowRequestInput) OptExecuteWorkflowRequestInput {
	return OptExecuteWorkflowRequestInput{
		Value: v,
		Set:   true,
	}
}

// OptExecuteWorkflowRequestInput is optional ExecuteWorkflowRequestInput.
type OptExecuteWorkflowRequestInput struct {
	Value ExecuteWorkflowRequestInput
	Set   bool
}

// IsSet returns true if OptExecuteWorkflowRequestInput was set.
func (o OptExecuteWorkflowRequestInput) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptExecuteWorkflowRequestInput) Reset() {
	var v ExecuteWorkflowRequestInput
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptExecuteWorkflowRequestInput) SetTo(v ExecuteWorkflowRequestInput) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptExecuteWorkflowRequestInput) Get() (v ExecuteWorkflowRequestInput, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptExecuteWorkflowRequestInput) Or(d ExecuteWorkflowRequestInput) ExecuteWorkflowRequestInput {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptExecutionInput returns new OptExecutionInput with value set to v.
func NewOptExecutionInput(v ExecutionInput) OptExecutionInput {
	return OptExecutionInput{
		Value: v,
		Set:   true,
	}
}

// OptExecutionInput is optional ExecutionInput.
type OptExecutionInput struct {
	Value ExecutionInput
	Set   bool
}

// IsSet returns true if OptExecutionInput was set.
func (o OptExecutionInput) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptExecutionInput) Reset() {
	var v ExecutionInput
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptExecutionInput) SetTo(v ExecutionInput) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptExecutionInput) Get() (v ExecutionInput, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptExecutionInput) Or(d ExecutionInput) ExecutionInput {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptExecutionOutput returns new OptExecutionOutput with value set to v.
func NewOptExecutionOutput(v ExecutionOutput) OptExecutionOutput {
	return OptExecutionOutput{
		Value: v,
		Set:   true,
	}
}

// OptExecutionOutput is optional ExecutionOutput.
type OptExecutionOutput struct {
	Value ExecutionOutput
	Set   bool
}

// IsSet returns true if OptExecutionOutput was set.
func (o OptExecutionOutput) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptExecutionOutput) Reset() {
	var v ExecutionOutput
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptExecutionOutput) SetTo(v ExecutionOutput) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptExecutionOutput) Get() (v ExecutionOutput, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptExecutionOutput) Or(d ExecutionOutput) ExecutionOutput {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptExecutionStatusQuery returns new OptExecutionStatusQuery with value set to v.
func NewOptExecutionStatusQuery(v ExecutionStatusQuery) OptExecutionStatusQuery {
	return OptExecutionStatusQuery{
		Value: v,
		Set:   true,
	}
}

// OptExecutionStatusQuery is optional ExecutionStatusQuery.
type OptExecutionStatusQuery struct {
	Value ExecutionStatusQuery
	Set   bool
}

// IsSet returns true if OptExecutionStatusQuery was set.
func (o OptExecutionStatusQuery) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptExecutionStatusQuery) Reset() {
	var v ExecutionStatusQuery
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptExecutionStatusQuery) SetTo(v ExecutionStatusQuery) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptExecutionStatusQuery) Get() (v ExecutionStatusQuery, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptExecutionStatusQuery) Or(d ExecutionStatusQuery) ExecutionStatusQuery {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptHealthStatusChecks returns new OptHealthStatusChecks with value set to v.
func NewOptHealthStatusChecks(v HealthStatusChecks) OptHealthStatusChecks {
	return OptHealthStatusChecks{
		Value: v,
		Set:   true,
	}
}

// OptHealthStatusChecks is optional HealthStatusChecks.
type OptHealthStatusChecks struct {
	Value HealthStatusChecks
	Set   bool
}

// IsSet returns true if OptHealthStatusChecks was set.
func (o OptHealthStatusChecks) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptHealthStatusChecks) Reset() {
	var v HealthStatusChecks
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptHealthStatusChecks) SetTo(v HealthStatusChecks) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptHealthStatusChecks) Get() (v HealthStatusChecks, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptHealthStatusChecks) Or(d HealthStatusChecks) HealthStatusChecks {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptListAlertsSeverity returns new OptListAlertsSeverity with value set to v.
func NewOptListAlertsSeverity(v ListAlertsSeverity) OptListAlertsSeverity {
	return OptListAlertsSeverity{
		Value: v,
		Set:   true,
	}
}

// OptListAlertsSeverity is optional ListAlertsSeverity.
type OptListAlertsSeverity struct {
	Value ListAlertsSeverity
	Set   bool
}

// IsSet returns true if OptListAlertsSeverity was set.
func (o OptListAlertsSeverity) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptListAlertsSeverity) Reset() {
	var v ListAlertsSeverity
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptListAlertsSeverity) SetTo(v ListAlertsSeverity) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptListAlertsSeverity) Get() (v ListAlertsSeverity, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptListAlertsSeverity) Or(d ListAlertsSeverity) ListAlertsSeverity {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptListAuditLogsAction returns new OptListAuditLogsAction with value set to v.
func NewOptListAuditLogsAction(v ListAuditLogsAction) OptListAuditLogsAction {
	return OptListAuditLogsAction{
		Value: v,
		Set:   true,
	}
}

// OptListAuditLogsAction is optional ListAuditLogsAction.
type OptListAuditLogsAction struct {
	Value ListAuditLogsAction
	Set   bool
}

// IsSet returns true if OptListAuditLogsAction was set.
func (o OptListAuditLogsAction) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptListAuditLogsAction) Reset() {
	var v ListAuditLogsAction
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptListAuditLogsAction) SetTo(v ListAuditLogsAction) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptListAuditLogsAction) Get() (v ListAuditLogsAction, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptListAuditLogsAction) Or(d ListAuditLogsAction) ListAuditLogsAction {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptListAuditLogsResourceType returns new OptListAuditLogsResourceType with value set to v.
func NewOptListAuditLogsResourceType(v ListAuditLogsResourceType) OptListAuditLogsResourceType {
	return OptListAuditLogsResourceType{
		Value: v,
		Set:   true,
	}
}

// OptListAuditLogsResourceType is optional ListAuditLogsResourceType.
type OptListAuditLogsResourceType struct {
	Value ListAuditLogsResourceType
	Set   bool
}

// IsSet returns true if OptListAuditLogsResourceType was set.
func (o OptListAuditLogsResourceType) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptListAuditLogsResourceType) Reset() {
	var v ListAuditLogsResourceType
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptListAuditLogsResourceType) SetTo(v ListAuditLogsResourceType) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptListAuditLogsResourceType) Get() (v ListAuditLogsResourceType, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptListAuditLogsResourceType) Or(d ListAuditLogsResourceType) ListAuditLogsResourceType {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilAuditLogNewValue returns new OptNilAuditLogNewValue with value set to v.
func NewOptNilAuditLogNewValue(v AuditLogNewValue) OptNilAuditLogNewValue {
	return OptNilAuditLogNewValue{
		Value: v,
		Set:   true,
	}
}

// OptNilAuditLogNewValue is optional nullable AuditLogNewValue.
type OptNilAuditLogNewValue struct {
	Value AuditLogNewValue
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilAuditLogNewValue was set.
func (o OptNilAuditLogNewValue) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilAuditLogNewValue) Reset() {
	var v AuditLogNewValue
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilAuditLogNewValue) SetTo(v AuditLogNewValue) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilAuditLogNewValue) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilAuditLogNewValue) SetToNull() {
	o.Set = true
	o.Null = true
	var v AuditLogNewValue
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilAuditLogNewValue) Get() (v AuditLogNewValue, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilAuditLogNewValue) Or(d AuditLogNewValue) AuditLogNewValue {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilAuditLogOldValue returns new OptNilAuditLogOldValue with value set to v.
func NewOptNilAuditLogOldValue(v AuditLogOldValue) OptNilAuditLogOldValue {
	return OptNilAuditLogOldValue{
		Value: v,
		Set:   true,
	}
}

// OptNilAuditLogOldValue is optional nullable AuditLogOldValue.
type OptNilAuditLogOldValue struct {
	Value AuditLogOldValue
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilAuditLogOldValue was set.
func (o OptNilAuditLogOldValue) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilAuditLogOldValue) Reset() {
	var v AuditLogOldValue
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilAuditLogOldValue) SetTo(v AuditLogOldValue) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilAuditLogOldValue) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilAuditLogOldValue) SetToNull() {
	o.Set = true
	o.Null = true
	var v AuditLogOldValue
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilAuditLogOldValue) Get() (v AuditLogOldValue, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilAuditLogOldValue) Or(d AuditLogOldValue) AuditLogOldValue {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilDateTime returns new OptNilDateTime with value set to v.
func NewOptNilDateTime(v time.Time) OptNilDateTime {
	return OptNilDateTime{
		Value: v,
		Set:   true,
	}
}

// OptNilDateTime is optional nullable time.Time.
type OptNilDateTime struct {
	Value time.Time
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilDateTime was set.
func (o OptNilDateTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilDateTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilDateTime) SetTo(v time.Time) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilDateTime) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilDateTime) SetToNull() {
	o.Set = true
	o.Null = true
	var v time.Time
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilDateTime) Get() (v time.Time, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilString returns new OptNilString with value set to v.
func NewOptNilString(v string) OptNilString {
	return OptNilString{
		Value: v,
		Set:   true,
	}
}

// OptNilString is optional nullable string.
type OptNilString struct {
	Value string
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilString was set.
func (o OptNilString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilString) Reset() {
	var v string
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilString) SetTo(v string) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilString) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilString) SetToNull() {
	o.Set = true
	o.Null = true
	var v string
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilString) Get() (v string, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilUUID returns new OptNilUUID with value set to v.
func NewOptNilUUID(v uuid.UUID) OptNilUUID {
	return OptNilUUID{
		Value: v,
		Set:   true,
	}
}

// OptNilUUID is optional nullable uuid.UUID.
type OptNilUUID struct {
	Value uuid.UUID
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilUUID was set.
func (o OptNilUUID) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilUUID) Reset() {
	var v uuid.UUID
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilUUID) SetTo(v uuid.UUID) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilUUID) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilUUID) SetToNull() {
	o.Set = true
	o.Null = true
	var v uuid.UUID
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilUUID) Get() (v uuid.UUID, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilUUID) Or(d uuid.UUID) uuid.UUID {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptUUID returns new OptUUID with value set to v.
func NewOptUUID(v uuid.UUID) OptUUID {
	return OptUUID{
		Value: v,
		Set:   true,
	}
}

// OptUUID is optional uuid.UUID.
type OptUUID struct {
	Value uuid.UUID
	Set   bool
}

// IsSet returns true if OptUUID was set.
func (o OptUUID) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUUID) Reset() {
	var v uuid.UUID
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUUID) SetTo(v uuid.UUID) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUUID) Get() (v uuid.UUID, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUUID) Or(d uuid.UUID) uuid.UUID {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptUpdateWorkflowRequestDefinition returns new OptUpdateWorkflowRequestDefinition with value set to v.
func NewOptUpdateWorkflowRequestDefinition(v UpdateWorkflowRequestDefinition) OptUpdateWorkflowRequestDefinition {
	return OptUpdateWorkflowRequestDefinition{
		Value: v,
		Set:   true,
	}
}

// OptUpdateWorkflowRequestDefinition is optional UpdateWorkflowRequestDefinition.
type OptUpdateWorkflowRequestDefinition struct {
	Value UpdateWorkflowRequestDefinition
	Set   bool
}

// IsSet returns true if OptUpdateWorkflowRequestDefinition was set.
func (o OptUpdateWorkflowRequestDefinition) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUpdateWorkflowRequestDefinition) Reset() {
	var v UpdateWorkflowRequestDefinition
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUpdateWorkflowRequestDefinition) SetTo(v UpdateWorkflowRequestDefinition) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUpdateWorkflowRequestDefinition) Get() (v UpdateWorkflowRequestDefinition, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUpdateWorkflowRequestDefinition) Or(d UpdateWorkflowRequestDefinition) UpdateWorkflowRequestDefinition {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptWorkflowStatus returns new OptWorkflowStatus with value set to v.
func NewOptWorkflowStatus(v WorkflowStatus) OptWorkflowStatus {
	return OptWorkflowStatus{
		Value: v,
		Set:   true,
	}
}

// OptWorkflowStatus is optional WorkflowStatus.
type OptWorkflowStatus struct {
	Value WorkflowStatus
	Set   bool
}

// IsSet returns true if OptWorkflowStatus was set.
func (o OptWorkflowStatus) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptWorkflowStatus) Reset() {
	var v WorkflowStatus
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptWorkflowStatus) SetTo(v WorkflowStatus) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptWorkflowStatus) Get() (v WorkflowStatus, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptWorkflowStatus) Or(d WorkflowStatus) WorkflowStatus {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptWorkflowStatusQuery returns new OptWorkflowStatusQuery with value set to v.
func NewOptWorkflowStatusQuery(v WorkflowStatusQuery) OptWorkflowStatusQuery {
	return OptWorkflowStatusQuery{
		Value: v,
		Set:   true,
	}
}

// OptWorkflowStatusQuery is optional WorkflowStatusQuery.
type OptWorkflowStatusQuery struct {
	Value WorkflowStatusQuery
	Set   bool
}

// IsSet returns true if OptWorkflowStatusQuery was set.
func (o OptWorkflowStatusQuery) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptWorkflowStatusQuery) Reset() {
	var v WorkflowStatusQuery
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptWorkflowStatusQuery) SetTo(v WorkflowStatusQuery) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptWorkflowStatusQuery) Get() (v WorkflowStatusQuery, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptWorkflowStatusQuery) Or(d WorkflowStatusQuery) WorkflowStatusQuery {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Paginated list of alerts.
// Ref: #/components/schemas/PaginatedAlerts
type PaginatedAlerts struct {
	Data  []Alert `json:"data"`
	Total int     `json:"total"`
	Page  int     `json:"page"`
	Limit int     `json:"limit"`
}

// GetData returns the value of Data.
func (s *PaginatedAlerts) GetData() []Alert {
	return s.Data
}

// GetTotal returns the value of Total.
func (s *PaginatedAlerts) GetTotal() int {
	return s.Total
}

// GetPage returns the value of Page.
func (s *PaginatedAlerts) GetPage() int {
	return s.Page
}

// GetLimit returns the value of Limit.
func (s *PaginatedAlerts) GetLimit() int {
	return s.Limit
}

// SetData sets the value of Data.
func (s *PaginatedAlerts) SetData(val []Alert) {
	s.Data = val
}

// SetTotal sets the value of Total.
func (s *PaginatedAlerts) SetTotal(val int) {
	s.Total = val
}

// SetPage sets the value of Page.
func (s *PaginatedAlerts) SetPage(val int) {
	s.Page = val
}

// SetLimit sets the value of Limit.
func (s *PaginatedAlerts) SetLimit(val int) {
	s.Limit = val
}

func (*PaginatedAlerts) listAlertsRes() {}

// Paginated list of audit logs.
// Ref: #/components/schemas/PaginatedAuditLogs
type PaginatedAuditLogs struct {
	Data  []AuditLog `json:"data"`
	Total int        `json:"total"`
	Page  int        `json:"page"`
	Limit int        `json:"limit"`
}

// GetData returns the value of Data.
func (s *PaginatedAuditLogs) GetData() []AuditLog {
	return s.Data
}

// GetTotal returns the value of Total.
func (s *PaginatedAuditLogs) GetTotal() int {
	return s.Total
}

// GetPage returns the value of Page.
func (s *PaginatedAuditLogs) GetPage() int {
	return s.Page
}

// GetLimit returns the value of Limit.
func (s *PaginatedAuditLogs) GetLimit() int {
	return s.Limit
}

// SetData sets the value of Data.
func (s *PaginatedAuditLogs) SetData(val []AuditLog) {
	s.Data = val
}

// SetTotal sets the value of Total.
func (s *PaginatedAuditLogs) SetTotal(val int) {
	s.Total = val
}

// SetPage sets the value of Page.
func (s *PaginatedAuditLogs) SetPage(val int) {
	s.Page = val
}

// SetLimit sets the value of Limit.
func (s *PaginatedAuditLogs) SetLimit(val int) {
	s.Limit = val
}

func (*PaginatedAuditLogs) listAuditLogsByResourceRes() {}
func (*PaginatedAuditLogs) listAuditLogsByUserRes()     {}
func (*PaginatedAuditLogs) listAuditLogsRes()           {}

// Paginated list of executions.
// Ref: #/components/schemas/PaginatedExecutions
type PaginatedExecutions struct {
	Data  []Execution `json:"data"`
	Total int         `json:"total"`
	Page  int         `json:"page"`
	Limit int         `json:"limit"`
}

// GetData returns the value of Data.
func (s *PaginatedExecutions) GetData() []Execution {
	return s.Data
}

// GetTotal returns the value of Total.
func (s *PaginatedExecutions) GetTotal() int {
	return s.Total
}

// GetPage returns the value of Page.
func (s *PaginatedExecutions) GetPage() int {
	return s.Page
}

// GetLimit returns the value of Limit.
func (s *PaginatedExecutions) GetLimit() int {
	return s.Limit
}

// SetData sets the value of Data.
func (s *PaginatedExecutions) SetData(val []Execution) {
	s.Data = val
}

// SetTotal sets the value of Total.
func (s *PaginatedExecutions) SetTotal(val int) {
	s.Total = val
}

// SetPage sets the value of Page.
func (s *PaginatedExecutions) SetPage(val int) {
	s.Page = val
}

// SetLimit sets the value of Limit.
func (s *PaginatedExecutions) SetLimit(val int) {
	s.Limit = val
}

func (*PaginatedExecutions) listExecutionsRes()         {}
func (*PaginatedExecutions) listWorkflowExecutionsRes() {}

// Paginated list of workflows.
// Ref: #/components/schemas/PaginatedWorkflows
type PaginatedWorkflows struct {
	Data []Workflow `json:"data"`
	// Total number of items.
	Total int `json:"total"`
	// Current page.
	Page int `json:"page"`
	// Items per page.
	Limit int `json:"limit"`
}

// GetData returns the value of Data.
func (s *PaginatedWorkflows) GetData() []Workflow {
	return s.Data
}

// GetTotal returns the value of Total.
func (s *PaginatedWorkflows) GetTotal() int {
	return s.Total
}

// GetPage returns the value of Page.
func (s *PaginatedWorkflows) GetPage() int {
	return s.Page
}

// GetLimit returns the value of Limit.
func (s *PaginatedWorkflows) GetLimit() int {
	return s.Limit
}

// SetData sets the value of Data.
func (s *PaginatedWorkflows) SetData(val []Workflow) {
	s.Data = val
}

// SetTotal sets the value of Total.
func (s *PaginatedWorkflows) SetTotal(val int) {
	s.Total = val
}

// SetPage sets the value of Page.
func (s *PaginatedWorkflows) SetPage(val int) {
	s.Page = val
}

// SetLimit sets the value of Limit.
func (s *PaginatedWorkflows) SetLimit(val int) {
	s.Limit = val
}

func (*PaginatedWorkflows) listWorkflowsRes() {}

type ReadinessProbeOK HealthStatus

func (*ReadinessProbeOK) readinessProbeRes() {}

type ReadinessProbeServiceUnavailable HealthStatus

func (*ReadinessProbeServiceUnavailable) readinessProbeRes() {}

type ResolveAlertInternalServerError Error

func (*ResolveAlertInternalServerError) resolveAlertRes() {}

type ResolveAlertNotFound Error

func (*ResolveAlertNotFound) resolveAlertRes() {}

type ResolveAlertUnauthorized Error

func (*ResolveAlertUnauthorized) resolveAlertRes() {}

type ResolveAlertUnprocessableEntity Error

func (*ResolveAlertUnprocessableEntity) resolveAlertRes() {}

type ResourceTypePath string

const (
	ResourceTypePathWorkflow  ResourceTypePath = "workflow"
	ResourceTypePathExecution ResourceTypePath = "execution"
	ResourceTypePathAlert     ResourceTypePath = "alert"
)

// AllValues returns all ResourceTypePath values.
func (ResourceTypePath) AllValues() []ResourceTypePath {
	return []ResourceTypePath{
		ResourceTypePathWorkflow,
		ResourceTypePathExecution,
		ResourceTypePathAlert,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ResourceTypePath) MarshalText() ([]byte, error) {
	switch s {
	case ResourceTypePathWorkflow:
		return []byte(s), nil
	case ResourceTypePathExecution:
		return []byte(s), nil
	case ResourceTypePathAlert:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ResourceTypePath) UnmarshalText(data []byte) error {
	switch ResourceTypePath(data) {
	case ResourceTypePathWorkflow:
		*s = ResourceTypePathWorkflow
		return nil
	case ResourceTypePathExecution:
		*s = ResourceTypePathExecution
		return nil
	case ResourceTypePathAlert:
		*s = ResourceTypePathAlert
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type UpdateWorkflowBadRequest Error

func (*UpdateWorkflowBadRequest) updateWorkflowRes() {}

type UpdateWorkflowInternalServerError Error

func (*UpdateWorkflowInternalServerError) updateWorkflowRes() {}

type UpdateWorkflowNotFound Error

func (*UpdateWorkflowNotFound) updateWorkflowRes() {}

// Request body for updating a workflow.
// Ref: #/components/schemas/UpdateWorkflowRequest
type UpdateWorkflowRequest struct {
	Name        OptString                          `json:"name"`
	Description OptString                          `json:"description"`
	Definition  OptUpdateWorkflowRequestDefinition `json:"definition"`
	Schedule    OptString                          `json:"schedule"`
	Status      OptWorkflowStatus                  `json:"status"`
}

// GetName returns the value of Name.
func (s *UpdateWorkflowRequest) GetName() OptString {
	return s.Name
}

// GetDescription returns the value of Description.
func (s *UpdateWorkflowRequest) GetDescription() OptString {
	return s.Description
}

// GetDefinition returns the value of Definition.
func (s *UpdateWorkflowRequest) GetDefinition() OptUpdateWorkflowRequestDefinition {
	return s.Definition
}

// GetSchedule returns the value of Schedule.
func (s *UpdateWorkflowRequest) GetSchedule() OptString {
	return s.Schedule
}

// GetStatus returns the value of Status.
func (s *UpdateWorkflowRequest) GetStatus() OptWorkflowStatus {
	return s.Status
}

// SetName sets the value of Name.
func (s *UpdateWorkflowRequest) SetName(val OptString) {
	s.Name = val
}

// SetDescription sets the value of Description.
func (s *UpdateWorkflowRequest) SetDescription(val OptString) {
	s.Description = val
}

// SetDefinition sets the value of Definition.
func (s *UpdateWorkflowRequest) SetDefinition(val OptUpdateWorkflowRequestDefinition) {
	s.Definition = val
}

// SetSchedule sets the value of Schedule.
func (s *UpdateWorkflowRequest) SetSchedule(val OptString) {
	s.Schedule = val
}

// SetStatus sets the value of Status.
func (s *UpdateWorkflowRequest) SetStatus(val OptWorkflowStatus) {
	s.Status = val
}

type UpdateWorkflowRequestDefinition map[string]jx.Raw

func (s *UpdateWorkflowRequestDefinition) init() UpdateWorkflowRequestDefinition {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

type UpdateWorkflowUnauthorized Error

func (*UpdateWorkflowUnauthorized) updateWorkflowRes() {}

// Workflow definition for orchestration.
// Ref: #/components/schemas/Workflow
type Workflow struct {
	// Unique workflow identifier.
	ID uuid.UUID `json:"id"`
	// Tenant identifier.
	TenantID uuid.UUID `json:"tenant_id"`
	// Workflow name.
	Name string `json:"name"`
	// Optional workflow description.
	Description OptString `json:"description"`
	// Workflow definition as JSON.
	Definition WorkflowDefinition `json:"definition"`
	// Cron expression for scheduled execution (e.g., "0 * * * *" or "@daily").
	Schedule OptString      `json:"schedule"`
	Status   WorkflowStatus `json:"status"`
	// Version number (auto-incremented on update).
	Version int `json:"version"`
	// User who created the workflow.
	CreatedBy OptUUID `json:"created_by"`
	// Creation timestamp.
	CreatedAt time.Time `json:"created_at"`
	// Last update timestamp.
	UpdatedAt time.Time `json:"updated_at"`
}

// GetID returns the value of ID.
func (s *Workflow) GetID() uuid.UUID {
	return s.ID
}

// GetTenantID returns the value of TenantID.
func (s *Workflow) GetTenantID() uuid.UUID {
	return s.TenantID
}

// GetName returns the value of Name.
func (s *Workflow) GetName() string {
	return s.Name
}

// GetDescription returns the value of Description.
func (s *Workflow) GetDescription() OptString {
	return s.Description
}

// GetDefinition returns the value of Definition.
func (s *Workflow) GetDefinition() WorkflowDefinition {
	return s.Definition
}

// GetSchedule returns the value of Schedule.
func (s *Workflow) GetSchedule() OptString {
	return s.Schedule
}

// GetStatus returns the value of Status.
func (s *Workflow) GetStatus() WorkflowStatus {
	return s.Status
}

// GetVersion returns the value of Version.
func (s *Workflow) GetVersion() int {
	return s.Version
}

// GetCreatedBy returns the value of CreatedBy.
func (s *Workflow) GetCreatedBy() OptUUID {
	return s.CreatedBy
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Workflow) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *Workflow) GetUpdatedAt() time.Time {
	return s.UpdatedAt
}

// SetID sets the value of ID.
func (s *Workflow) SetID(val uuid.UUID) {
	s.ID = val
}

// SetTenantID sets the value of TenantID.
func (s *Workflow) SetTenantID(val uuid.UUID) {
	s.TenantID = val
}

// SetName sets the value of Name.
func (s *Workflow) SetName(val string) {
	s.Name = val
}

// SetDescription sets the value of Description.
func (s *Workflow) SetDescription(val OptString) {
	s.Description = val
}

// SetDefinition sets the value of Definition.
func (s *Workflow) SetDefinition(val WorkflowDefinition) {
	s.Definition = val
}

// SetSchedule sets the value of Schedule.
func (s *Workflow) SetSchedule(val OptString) {
	s.Schedule = val
}

// SetStatus sets the value of Status.
func (s *Workflow) SetStatus(val WorkflowStatus) {
	s.Status = val
}

// SetVersion sets the value of Version.
func (s *Workflow) SetVersion(val int) {
	s.Version = val
}

// SetCreatedBy sets the value of CreatedBy.
func (s *Workflow) SetCreatedBy(val OptUUID) {
	s.CreatedBy = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Workflow) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *Workflow) SetUpdatedAt(val time.Time) {
	s.UpdatedAt = val
}

// Workflow definition as JSON.
type WorkflowDefinition map[string]jx.Raw

func (s *WorkflowDefinition) init() WorkflowDefinition {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

// Single workflow response wrapper.
// Ref: #/components/schemas/WorkflowResponse
type WorkflowResponse struct {
	Data Workflow `json:"data"`
}

// GetData returns the value of Data.
func (s *WorkflowResponse) GetData() Workflow {
	return s.Data
}

// SetData sets the value of Data.
func (s *WorkflowResponse) SetData(val Workflow) {
	s.Data = val
}

func (*WorkflowResponse) createWorkflowRes() {}
func (*WorkflowResponse) getWorkflowRes()    {}
func (*WorkflowResponse) updateWorkflowRes() {}

// Workflow status.
// Ref: #/components/schemas/WorkflowStatus
type WorkflowStatus string

const (
	WorkflowStatusActive   WorkflowStatus = "active"
	WorkflowStatusInactive WorkflowStatus = "inactive"
	WorkflowStatusDraft    WorkflowStatus = "draft"
)

// AllValues returns all WorkflowStatus values.
func (WorkflowStatus) AllValues() []WorkflowStatus {
	return []WorkflowStatus{
		WorkflowStatusActive,
		WorkflowStatusInactive,
		WorkflowStatusDraft,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s WorkflowStatus) MarshalText() ([]byte, error) {
	switch s {
	case WorkflowStatusActive:
		return []byte(s), nil
	case WorkflowStatusInactive:
		return []byte(s), nil
	case WorkflowStatusDraft:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *WorkflowStatus) UnmarshalText(data []byte) error {
	switch WorkflowStatus(data) {
	case WorkflowStatusActive:
		*s = WorkflowStatusActive
		return nil
	case WorkflowStatusInactive:
		*s = WorkflowStatusInactive
		return nil
	case WorkflowStatusDraft:
		*s = WorkflowStatusDraft
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type WorkflowStatusQuery string

const (
	WorkflowStatusQueryActive   WorkflowStatusQuery = "active"
	WorkflowStatusQueryInactive WorkflowStatusQuery = "inactive"
	WorkflowStatusQueryDraft    WorkflowStatusQuery = "draft"
)

// AllValues returns all WorkflowStatusQuery values.
func (WorkflowStatusQuery) AllValues() []WorkflowStatusQuery {
	return []WorkflowStatusQuery{
		WorkflowStatusQueryActive,
		WorkflowStatusQueryInactive,
		WorkflowStatusQueryDraft,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s WorkflowStatusQuery) MarshalText() ([]byte, error) {
	switch s {
	case WorkflowStatusQueryActive:
		return []byte(s), nil
	case WorkflowStatusQueryInactive:
		return []byte(s), nil
	case WorkflowStatusQueryDraft:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *WorkflowStatusQuery) UnmarshalText(data []byte) error {
	switch WorkflowStatusQuery(data) {
	case WorkflowStatusQueryActive:
		*s = WorkflowStatusQueryActive
		return nil
	case WorkflowStatusQueryInactive:
		*s = WorkflowStatusQueryInactive
		return nil
	case WorkflowStatusQueryDraft:
		*s = WorkflowStatusQueryDraft
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}
