linters:
  disable:
    - errcheck
  enable:
    - govet
    - staticcheck
    - unused

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
