// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"encoding/json"
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Alert struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	TenantID       uuid.UUID          `db:"tenant_id" json:"tenant_id"`
	WorkflowID     pgtype.UUID        `db:"workflow_id" json:"workflow_id"`
	ExecutionID    pgtype.UUID        `db:"execution_id" json:"execution_id"`
	Severity       string             `db:"severity" json:"severity"`
	Title          string             `db:"title" json:"title"`
	Message        *string            `db:"message" json:"message"`
	Status         string             `db:"status" json:"status"`
	AcknowledgedAt pgtype.Timestamptz `db:"acknowledged_at" json:"acknowledged_at"`
	AcknowledgedBy pgtype.UUID        `db:"acknowledged_by" json:"acknowledged_by"`
	ResolvedAt     pgtype.Timestamptz `db:"resolved_at" json:"resolved_at"`
	ResolvedBy     pgtype.UUID        `db:"resolved_by" json:"resolved_by"`
	CreatedAt      time.Time          `db:"created_at" json:"created_at"`
}

type AuditLog struct {
	ID           uuid.UUID   `db:"id" json:"id"`
	TenantID     uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	UserID       pgtype.UUID `db:"user_id" json:"user_id"`
	EventType    string      `db:"event_type" json:"event_type"`
	ResourceType string      `db:"resource_type" json:"resource_type"`
	ResourceID   pgtype.UUID `db:"resource_id" json:"resource_id"`
	Action       string      `db:"action" json:"action"`
	OldValue     []byte      `db:"old_value" json:"old_value"`
	NewValue     []byte      `db:"new_value" json:"new_value"`
	IpAddress    *netip.Addr `db:"ip_address" json:"ip_address"`
	UserAgent    *string     `db:"user_agent" json:"user_agent"`
	CreatedAt    time.Time   `db:"created_at" json:"created_at"`
}

type Execution struct {
	ID                 uuid.UUID          `db:"id" json:"id"`
	TenantID           uuid.UUID          `db:"tenant_id" json:"tenant_id"`
	WorkflowID         uuid.UUID          `db:"workflow_id" json:"workflow_id"`
	TemporalWorkflowID *string            `db:"temporal_workflow_id" json:"temporal_workflow_id"`
	TemporalRunID      *string            `db:"temporal_run_id" json:"temporal_run_id"`
	Status             string             `db:"status" json:"status"`
	Input              []byte             `db:"input" json:"input"`
	Output             []byte             `db:"output" json:"output"`
	Error              *string            `db:"error" json:"error"`
	StartedAt          pgtype.Timestamptz `db:"started_at" json:"started_at"`
	CompletedAt        pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	CreatedBy          pgtype.UUID        `db:"created_by" json:"created_by"`
	CreatedAt          time.Time          `db:"created_at" json:"created_at"`
}

type Metric struct {
	ID        uuid.UUID `db:"id" json:"id"`
	TenantID  uuid.UUID `db:"tenant_id" json:"tenant_id"`
	Name      string    `db:"name" json:"name"`
	Value     float64   `db:"value" json:"value"`
	Labels    []byte    `db:"labels" json:"labels"`
	Source    *string   `db:"source" json:"source"`
	Timestamp time.Time `db:"timestamp" json:"timestamp"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}

type MetricDefinition struct {
	ID             uuid.UUID `db:"id" json:"id"`
	TenantID       uuid.UUID `db:"tenant_id" json:"tenant_id"`
	Name           string    `db:"name" json:"name"`
	DisplayName    *string   `db:"display_name" json:"display_name"`
	Description    *string   `db:"description" json:"description"`
	Unit           *string   `db:"unit" json:"unit"`
	Type           string    `db:"type" json:"type"`
	Aggregation    *string   `db:"aggregation" json:"aggregation"`
	AlertThreshold []byte    `db:"alert_threshold" json:"alert_threshold"`
	CreatedAt      time.Time `db:"created_at" json:"created_at"`
	UpdatedAt      time.Time `db:"updated_at" json:"updated_at"`
}

type Tenant struct {
	ID        uuid.UUID `db:"id" json:"id"`
	Name      string    `db:"name" json:"name"`
	Slug      string    `db:"slug" json:"slug"`
	Plan      string    `db:"plan" json:"plan"`
	Settings  []byte    `db:"settings" json:"settings"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"`
}

type User struct {
	ID         uuid.UUID `db:"id" json:"id"`
	TenantID   uuid.UUID `db:"tenant_id" json:"tenant_id"`
	ExternalID string    `db:"external_id" json:"external_id"`
	Email      string    `db:"email" json:"email"`
	Name       *string   `db:"name" json:"name"`
	Roles      []string  `db:"roles" json:"roles"`
	CreatedAt  time.Time `db:"created_at" json:"created_at"`
	UpdatedAt  time.Time `db:"updated_at" json:"updated_at"`
}

type Workflow struct {
	ID          uuid.UUID       `db:"id" json:"id"`
	TenantID    uuid.UUID       `db:"tenant_id" json:"tenant_id"`
	Name        string          `db:"name" json:"name"`
	Description *string         `db:"description" json:"description"`
	Definition  json.RawMessage `db:"definition" json:"definition"`
	Schedule    *string         `db:"schedule" json:"schedule"`
	Status      string          `db:"status" json:"status"`
	Version     int32           `db:"version" json:"version"`
	CreatedBy   pgtype.UUID     `db:"created_by" json:"created_by"`
	CreatedAt   time.Time       `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time       `db:"updated_at" json:"updated_at"`
}
