// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AcknowledgeAlert(ctx context.Context, arg AcknowledgeAlertParams) (Alert, error)
	CompleteExecution(ctx context.Context, arg CompleteExecutionParams) (Execution, error)
	CountAlertRules(ctx context.Context, tenantID uuid.UUID) (int64, error)
	CountAlerts(ctx context.Context, tenantID uuid.UUID) (int64, error)
	CountAlertsByStatus(ctx context.Context, arg CountAlertsByStatusParams) (int64, error)
	CountAuditLogsByTenant(ctx context.Context, tenantID uuid.UUID) (int64, error)
	CountExecutions(ctx context.Context, tenantID uuid.UUID) (int64, error)
	CountExecutionsByStatus(ctx context.Context, arg CountExecutionsByStatusParams) (int64, error)
	CountMetricDefinitions(ctx context.Context, tenantID uuid.UUID) (int64, error)
	CountMetrics(ctx context.Context, arg CountMetricsParams) (int64, error)
	CountOpenAlertsBySeverity(ctx context.Context, tenantID uuid.UUID) ([]CountOpenAlertsBySeverityRow, error)
	CountTenants(ctx context.Context) (int64, error)
	CountUsersByTenant(ctx context.Context, tenantID uuid.UUID) (int64, error)
	CountWorkflows(ctx context.Context, tenantID uuid.UUID) (int64, error)
	CountWorkflowsByStatus(ctx context.Context, arg CountWorkflowsByStatusParams) (int64, error)
	CreateAlert(ctx context.Context, arg CreateAlertParams) (Alert, error)
	CreateAlertRule(ctx context.Context, arg CreateAlertRuleParams) (AlertRule, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error)
	CreateExecution(ctx context.Context, arg CreateExecutionParams) (Execution, error)
	// Metric Definitions
	CreateMetricDefinition(ctx context.Context, arg CreateMetricDefinitionParams) (MetricDefinition, error)
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWorkflow(ctx context.Context, arg CreateWorkflowParams) (Workflow, error)
	DeleteAlertRule(ctx context.Context, arg DeleteAlertRuleParams) error
	DeleteMetricDefinition(ctx context.Context, arg DeleteMetricDefinitionParams) error
	DeleteOldMetrics(ctx context.Context, arg DeleteOldMetricsParams) error
	DeleteTenant(ctx context.Context, id uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	DeleteWorkflow(ctx context.Context, id uuid.UUID) error
	FailExecution(ctx context.Context, arg FailExecutionParams) (Execution, error)
	GetAlert(ctx context.Context, id uuid.UUID) (Alert, error)
	GetAlertRule(ctx context.Context, arg GetAlertRuleParams) (AlertRule, error)
	GetAlertRulesForMetric(ctx context.Context, arg GetAlertRulesForMetricParams) ([]AlertRule, error)
	GetExecution(ctx context.Context, id uuid.UUID) (Execution, error)
	GetExecutionByTemporalID(ctx context.Context, temporalWorkflowID *string) (Execution, error)
	GetExecutionStats(ctx context.Context, arg GetExecutionStatsParams) (GetExecutionStatsRow, error)
	GetLatestMetric(ctx context.Context, arg GetLatestMetricParams) (Metric, error)
	GetMetricDefinition(ctx context.Context, arg GetMetricDefinitionParams) (MetricDefinition, error)
	GetMetricNames(ctx context.Context, tenantID uuid.UUID) ([]string, error)
	GetMetricNamesWithPrefix(ctx context.Context, arg GetMetricNamesWithPrefixParams) ([]string, error)
	GetMetrics(ctx context.Context, arg GetMetricsParams) ([]Metric, error)
	GetMetricsAggregate(ctx context.Context, arg GetMetricsAggregateParams) (GetMetricsAggregateRow, error)
	GetMetricsAggregateWithPercentiles(ctx context.Context, arg GetMetricsAggregateWithPercentilesParams) (GetMetricsAggregateWithPercentilesRow, error)
	GetMetricsByLabels(ctx context.Context, arg GetMetricsByLabelsParams) ([]Metric, error)
	// Daily Pre-aggregated Data (from continuous aggregate)
	GetMetricsDaily(ctx context.Context, arg GetMetricsDailyParams) ([]MetricsDaily, error)
	// Hourly Pre-aggregated Data (from continuous aggregate)
	GetMetricsHourly(ctx context.Context, arg GetMetricsHourlyParams) ([]MetricsHourly, error)
	// TimescaleDB Time Bucket Queries
	GetMetricsSeries(ctx context.Context, arg GetMetricsSeriesParams) ([]GetMetricsSeriesRow, error)
	GetMetricsSeriesWithLabels(ctx context.Context, arg GetMetricsSeriesWithLabelsParams) ([]GetMetricsSeriesWithLabelsRow, error)
	GetScheduledWorkflows(ctx context.Context) ([]Workflow, error)
	GetTenant(ctx context.Context, id uuid.UUID) (Tenant, error)
	GetTenantBySlug(ctx context.Context, slug string) (Tenant, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (User, error)
	GetUserByExternalID(ctx context.Context, arg GetUserByExternalIDParams) (User, error)
	GetWorkflow(ctx context.Context, id uuid.UUID) (Workflow, error)
	InsertMetric(ctx context.Context, arg InsertMetricParams) (Metric, error)
	InsertMetricsBatch(ctx context.Context, arg []InsertMetricsBatchParams) (int64, error)
	ListAlertRules(ctx context.Context, arg ListAlertRulesParams) ([]AlertRule, error)
	ListAlertRulesByConditionType(ctx context.Context, arg ListAlertRulesByConditionTypeParams) ([]AlertRule, error)
	ListAlerts(ctx context.Context, arg ListAlertsParams) ([]Alert, error)
	ListAlertsBySeverity(ctx context.Context, arg ListAlertsBySeverityParams) ([]Alert, error)
	ListAlertsByStatus(ctx context.Context, arg ListAlertsByStatusParams) ([]Alert, error)
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error)
	ListAuditLogsByDateRange(ctx context.Context, arg ListAuditLogsByDateRangeParams) ([]AuditLog, error)
	ListAuditLogsByEventType(ctx context.Context, arg ListAuditLogsByEventTypeParams) ([]AuditLog, error)
	ListAuditLogsByResource(ctx context.Context, arg ListAuditLogsByResourceParams) ([]AuditLog, error)
	ListAuditLogsByUser(ctx context.Context, arg ListAuditLogsByUserParams) ([]AuditLog, error)
	ListEnabledAlertRules(ctx context.Context, tenantID uuid.UUID) ([]AlertRule, error)
	ListExecutions(ctx context.Context, arg ListExecutionsParams) ([]Execution, error)
	ListExecutionsByStatus(ctx context.Context, arg ListExecutionsByStatusParams) ([]Execution, error)
	ListExecutionsByWorkflow(ctx context.Context, arg ListExecutionsByWorkflowParams) ([]Execution, error)
	ListMetricDefinitions(ctx context.Context, arg ListMetricDefinitionsParams) ([]MetricDefinition, error)
	ListOpenAlerts(ctx context.Context, arg ListOpenAlertsParams) ([]Alert, error)
	ListRecentExecutions(ctx context.Context, arg ListRecentExecutionsParams) ([]Execution, error)
	ListTenants(ctx context.Context, arg ListTenantsParams) ([]Tenant, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	ListWorkflows(ctx context.Context, arg ListWorkflowsParams) ([]Workflow, error)
	ListWorkflowsByStatus(ctx context.Context, arg ListWorkflowsByStatusParams) ([]Workflow, error)
	ResolveAlert(ctx context.Context, arg ResolveAlertParams) (Alert, error)
	UpdateAlertRule(ctx context.Context, arg UpdateAlertRuleParams) (AlertRule, error)
	UpdateAlertRuleLastTriggered(ctx context.Context, id uuid.UUID) error
	UpdateAlertTriggeredExecution(ctx context.Context, arg UpdateAlertTriggeredExecutionParams) error
	UpdateExecutionRunID(ctx context.Context, arg UpdateExecutionRunIDParams) error
	UpdateExecutionStatus(ctx context.Context, arg UpdateExecutionStatusParams) error
	UpdateExecutionTemporalIDs(ctx context.Context, arg UpdateExecutionTemporalIDsParams) error
	UpdateMetricDefinition(ctx context.Context, arg UpdateMetricDefinitionParams) (MetricDefinition, error)
	UpdateTenant(ctx context.Context, arg UpdateTenantParams) (Tenant, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateWorkflow(ctx context.Context, arg UpdateWorkflowParams) (Workflow, error)
	UpdateWorkflowStatus(ctx context.Context, arg UpdateWorkflowStatusParams) (Workflow, error)
	UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
