// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AcknowledgeAlert(ctx context.Context, arg AcknowledgeAlertParams) (Alert, error)
	CompleteExecution(ctx context.Context, arg CompleteExecutionParams) (Execution, error)
	CountAlerts(ctx context.Context, tenantID uuid.UUID) (int64, error)
	CountAlertsByStatus(ctx context.Context, arg CountAlertsByStatusParams) (int64, error)
	CountAuditLogsByTenant(ctx context.Context, tenantID uuid.UUID) (int64, error)
	CountExecutions(ctx context.Context, tenantID uuid.UUID) (int64, error)
	CountExecutionsByStatus(ctx context.Context, arg CountExecutionsByStatusParams) (int64, error)
	CountOpenAlertsBySeverity(ctx context.Context, tenantID uuid.UUID) ([]CountOpenAlertsBySeverityRow, error)
	CountTenants(ctx context.Context) (int64, error)
	CountUsersByTenant(ctx context.Context, tenantID uuid.UUID) (int64, error)
	CountWorkflows(ctx context.Context, tenantID uuid.UUID) (int64, error)
	CountWorkflowsByStatus(ctx context.Context, arg CountWorkflowsByStatusParams) (int64, error)
	CreateAlert(ctx context.Context, arg CreateAlertParams) (Alert, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error)
	CreateExecution(ctx context.Context, arg CreateExecutionParams) (Execution, error)
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWorkflow(ctx context.Context, arg CreateWorkflowParams) (Workflow, error)
	DeleteTenant(ctx context.Context, id uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	DeleteWorkflow(ctx context.Context, id uuid.UUID) error
	FailExecution(ctx context.Context, arg FailExecutionParams) (Execution, error)
	GetAlert(ctx context.Context, id uuid.UUID) (Alert, error)
	GetExecution(ctx context.Context, id uuid.UUID) (Execution, error)
	GetExecutionByTemporalID(ctx context.Context, temporalWorkflowID *string) (Execution, error)
	GetExecutionStats(ctx context.Context, arg GetExecutionStatsParams) (GetExecutionStatsRow, error)
	GetScheduledWorkflows(ctx context.Context) ([]Workflow, error)
	GetTenant(ctx context.Context, id uuid.UUID) (Tenant, error)
	GetTenantBySlug(ctx context.Context, slug string) (Tenant, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (User, error)
	GetUserByExternalID(ctx context.Context, arg GetUserByExternalIDParams) (User, error)
	GetWorkflow(ctx context.Context, id uuid.UUID) (Workflow, error)
	ListAlerts(ctx context.Context, arg ListAlertsParams) ([]Alert, error)
	ListAlertsBySeverity(ctx context.Context, arg ListAlertsBySeverityParams) ([]Alert, error)
	ListAlertsByStatus(ctx context.Context, arg ListAlertsByStatusParams) ([]Alert, error)
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error)
	ListAuditLogsByDateRange(ctx context.Context, arg ListAuditLogsByDateRangeParams) ([]AuditLog, error)
	ListAuditLogsByEventType(ctx context.Context, arg ListAuditLogsByEventTypeParams) ([]AuditLog, error)
	ListAuditLogsByResource(ctx context.Context, arg ListAuditLogsByResourceParams) ([]AuditLog, error)
	ListAuditLogsByUser(ctx context.Context, arg ListAuditLogsByUserParams) ([]AuditLog, error)
	ListExecutions(ctx context.Context, arg ListExecutionsParams) ([]Execution, error)
	ListExecutionsByStatus(ctx context.Context, arg ListExecutionsByStatusParams) ([]Execution, error)
	ListExecutionsByWorkflow(ctx context.Context, arg ListExecutionsByWorkflowParams) ([]Execution, error)
	ListOpenAlerts(ctx context.Context, arg ListOpenAlertsParams) ([]Alert, error)
	ListRecentExecutions(ctx context.Context, arg ListRecentExecutionsParams) ([]Execution, error)
	ListTenants(ctx context.Context, arg ListTenantsParams) ([]Tenant, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	ListWorkflows(ctx context.Context, arg ListWorkflowsParams) ([]Workflow, error)
	ListWorkflowsByStatus(ctx context.Context, arg ListWorkflowsByStatusParams) ([]Workflow, error)
	ResolveAlert(ctx context.Context, arg ResolveAlertParams) (Alert, error)
	UpdateExecutionStatus(ctx context.Context, arg UpdateExecutionStatusParams) (Execution, error)
	UpdateExecutionTemporalIDs(ctx context.Context, arg UpdateExecutionTemporalIDsParams) error
	UpdateTenant(ctx context.Context, arg UpdateTenantParams) (Tenant, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateWorkflow(ctx context.Context, arg UpdateWorkflowParams) (Workflow, error)
	UpdateWorkflowStatus(ctx context.Context, arg UpdateWorkflowStatusParams) (Workflow, error)
	UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
