// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countUsersByTenant = `-- name: CountUsersByTenant :one
SELECT COUNT(*) FROM users WHERE tenant_id = $1
`

func (q *Queries) CountUsersByTenant(ctx context.Context, tenantID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersByTenant, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (tenant_id, external_id, email, name, roles)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, external_id, email, name, roles, created_at, updated_at
`

type CreateUserParams struct {
	TenantID   uuid.UUID `db:"tenant_id" json:"tenant_id"`
	ExternalID string    `db:"external_id" json:"external_id"`
	Email      string    `db:"email" json:"email"`
	Name       *string   `db:"name" json:"name"`
	Roles      []string  `db:"roles" json:"roles"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.TenantID,
		arg.ExternalID,
		arg.Email,
		arg.Name,
		arg.Roles,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ExternalID,
		&i.Email,
		&i.Name,
		&i.Roles,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, tenant_id, external_id, email, name, roles, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ExternalID,
		&i.Email,
		&i.Name,
		&i.Roles,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, tenant_id, external_id, email, name, roles, created_at, updated_at FROM users WHERE email = $1 AND tenant_id = $2
`

type GetUserByEmailParams struct {
	Email    string    `db:"email" json:"email"`
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, arg.Email, arg.TenantID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ExternalID,
		&i.Email,
		&i.Name,
		&i.Roles,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByExternalID = `-- name: GetUserByExternalID :one
SELECT id, tenant_id, external_id, email, name, roles, created_at, updated_at FROM users WHERE external_id = $1 AND tenant_id = $2
`

type GetUserByExternalIDParams struct {
	ExternalID string    `db:"external_id" json:"external_id"`
	TenantID   uuid.UUID `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) GetUserByExternalID(ctx context.Context, arg GetUserByExternalIDParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByExternalID, arg.ExternalID, arg.TenantID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ExternalID,
		&i.Email,
		&i.Name,
		&i.Roles,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, tenant_id, external_id, email, name, roles, created_at, updated_at FROM users
WHERE tenant_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListUsersParams struct {
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
	Limit    int32     `db:"limit" json:"limit"`
	Offset   int32     `db:"offset" json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ExternalID,
			&i.Email,
			&i.Name,
			&i.Roles,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET email = $2, name = $3, roles = $4
WHERE id = $1
RETURNING id, tenant_id, external_id, email, name, roles, created_at, updated_at
`

type UpdateUserParams struct {
	ID    uuid.UUID `db:"id" json:"id"`
	Email string    `db:"email" json:"email"`
	Name  *string   `db:"name" json:"name"`
	Roles []string  `db:"roles" json:"roles"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.Name,
		arg.Roles,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ExternalID,
		&i.Email,
		&i.Name,
		&i.Roles,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (tenant_id, external_id, email, name, roles)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (tenant_id, external_id)
DO UPDATE SET email = $3, name = $4, roles = $5, updated_at = NOW()
RETURNING id, tenant_id, external_id, email, name, roles, created_at, updated_at
`

type UpsertUserParams struct {
	TenantID   uuid.UUID `db:"tenant_id" json:"tenant_id"`
	ExternalID string    `db:"external_id" json:"external_id"`
	Email      string    `db:"email" json:"email"`
	Name       *string   `db:"name" json:"name"`
	Roles      []string  `db:"roles" json:"roles"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser,
		arg.TenantID,
		arg.ExternalID,
		arg.Email,
		arg.Name,
		arg.Roles,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ExternalID,
		&i.Email,
		&i.Name,
		&i.Roles,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
